version: "2.4"
services:
  cpp-ml-server:
    container_name: cpp-ml-server
    image: haritsahm/cpp-ml-server:1.2.0-all
    command: [ "/bin/bash" ]
    network_mode: "host"
    volumes:
      - ./triton-ml-server/model-repository:/model-repository
